spring:
  application:
    name: micro-product
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:product
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create

server:
  port: 8081