spring:
  application:
    name: micro-product
  datasource:
    url: jdbc:postgresql://localhost:5432/productdb
    username: root
    password: 123456789
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect


server:
  port: 8081